# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bond',
            new_name='contract',
        ),
    ]
