# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160513_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_contact',
            name='member',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='myapp.Member'),
        ),
    ]
