# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_members_contact_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
