# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160517_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='contract',
            new_name='contract_details',
        ),
        migrations.AlterField(
            model_name='member',
            name='contract_details',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='myapp.Contract'),
        ),
    ]
