# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20160517_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contract_details',
        ),
    ]
