# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20160517_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='members_contact',
            name='member',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
