# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20160518_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_contact',
            name='group_code',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='myapp.Members_contact'),
        ),
    ]
