# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20160519_0831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
